spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-management-db
    username: root
    password: scott
tatamotors.companyNo: 9168163508
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8086/eureka      
